services:
  nginx:
    image: nginx:1.25-alpine
    container_name: nginx-blog
    ports:
      - "80:80"
      - "443:443"
    environment:
      - DOMAIN=${DOMAIN}
      - VLESS_PATH=${VLESS_PATH}
      - V2RAY_PORT=${V2RAY_PORT}
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/site.conf.template:/etc/nginx/templates/site.conf.template:ro
      - ./html:/usr/share/nginx/html:ro
      - ./certs:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - v2ray
    restart: unless-stopped

  v2ray:
    image: v2fly/v2fly-core:v5.41.0
    container_name: v2ray
    volumes:
      - ./v2ray/config.json:/etc/v2ray/config.json:ro
    command: ["run", "-config", "/etc/v2ray/config.json"]
    restart: unless-stopped


  # 循环续期
  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    environment:
      - DOMAIN=${DOMAIN}
      - LE_EMAIL=${LE_EMAIL}
    volumes:
      - ./certs:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
      - /var/run/docker.sock:/var/run/docker.sock:ro
    entrypoint: /bin/sh
    command: >
      -c "trap exit TERM;
          while :; do
            certbot renew --webroot -w /var/www/certbot --quiet
              --deploy-hook 'docker exec nginx-blog nginx -s reload';
            sleep 12h;
          done"
    restart: unless-stopped

  certbot-init:
    image: certbot/certbot:latest
    profiles: ["init"]
    environment:
      - DOMAIN=${DOMAIN}
      - LE_EMAIL=${LE_EMAIL}
    volumes:
      - ./certs:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: certbot
